# Generated by Django 3.1.7 on 2021-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadbhavna', '0003_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='causes')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('raised', models.IntegerField(blank=True, default=0, null=True)),
                ('goal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
