# Generated by Django 3.1.7 on 2021-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadbhavna', '0004_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='latestNews')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
