# Generated by Django 3.1.7 on 2021-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadbhavna', '0006_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('desc', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
    ]
